language: java

jdk:
  - openjdk11

script:
 - cd lsdn
 - mvn -B test jacoco:report coveralls:report -DskipTests=false -Dmaven.test.failure.ignore=true
 
branches:
  only:
    - master

notifications:
  email:
    recipients:
      - kalee@kalriz.me
