language: java
jdk:
  - openjdk11

before_install:
  - chmod +x mvn
  
branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2

# mvn -B test
script: mvn -B test


# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - kalee@kalriz.me
